### ISSUE TITLE
Logo doesn't load

### ISSUE THREAD

**Issue by cedroid09** [usememos/memos#1446]
### Describe the bug

Hello,

usememos instance cannot load `https://usememos.com/logo.png` which causes the logo to not render.
Please check, maybe this commit is to blame: #1442 

### Steps to reproduce

Homepage

### Screenshots or additional context

![image](https://user-images.githubusercontent.com/3629558/229366308-82b3c82b-ff30-4eb0-9449-c8366b8995bd.png)

**Comment by boojack** [comment]
It's mainly because the format of logo has been updated to `webp`. `https://usememos.com/logo.png` -> `https://usememos.com/logo.webp`

You can download or upload yourself avatar in the user setting dialog.

<img width="751" alt="image" src="https://user-images.githubusercontent.com/24653555/229390575-eda22bcb-7acd-498c-9285-87e5f481c791.png">
