### ISSUE TITLE
Browser page blank with reversing proxy to a subdirectory 反向代理页面空白

### ISSUE THREAD

**Issue by mojave2** [usememos/memos#1748]
### Describe the bug

在设置反向代理时，如果设置的是**根目录**代理，可以正常访问；但使用**二级目录**设置代理的话，网页空白，但 curl 返回结果是正常的。

### Steps to reproduce

二级目录代理的设置如下
```
server {
    server_name your-domain-name.com;

    location /memos/ {
        proxy_pass http://localhost:5230/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
```

**Comment by Seevil** [comment]
前后端分离的都回这样，前端路由设置死了，不是相对路径，你要会改的话改为相对路径就好了，你F12看下就明白了

**Comment by kevinwenyu** [comment]
可是要怎么改呢？ @Seevil

**Comment by kevinwenyu** [comment]
v0.13.2 版本貌似还是空白，或者是哪里需要重新设置一下。
Version 0.13.2 is still blank page if set sub domain. or is there any setting should be changed in nginx proxy?
my revers proxy setting is below:
 #Memos
        location /memos/ {
        proxy_pass http://localhost:10001/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        }

**Comment by fhaubold** [comment]
Hello, I have the same problem. I deployed the app via Docker and set up a reverse proxy (Apache) for `domain.com/memos`. The HTML loads with 200, but the page is blank, and in the developer tools I can see that the paths to CSS and JS are wrong:

`domain.com/styles.css` instead of `domain.com/memos/styles.css`

Is there any solution for that? Thank you!

**Comment by lclrc** [comment]
@boojack 这个 issue 需要重新打开，之前那个 PR 被 revert 了 #1806

**Comment by kevinwenyu** [comment]
那这个issue解决了吗？

**Comment by Qeynos** [comment]
@boojack could you please reopen this issues, i have to hide memos in special uri to escape ISP review, the previous PR was reverted

**Comment by ulonger** [comment]
The issue is still there.

**Comment by kevinwenyu** [comment]
> The issue is still there.

and it seems no one wanna fix it.

**Comment by H-Cao** [comment]
> Hello, I have the same problem. I deployed the app via Docker and set up a reverse proxy (Apache) for `domain.com/memos`. The HTML loads with 200, but the page is blank, and in the developer tools I can see that the paths to CSS and JS are wrong:
> 
> `domain.com/styles.css` instead of `domain.com/memos/styles.css`
> 
> Is there any solution for that? Thank you!

This is indeed the culprit. If there is a ```location /memos/``` block in the nginx config file, when the browser accesses ```https://domain-name.com/memos```, the https request will be forwarded to ```http://localhost:5230/``` to load the initial page. However, some subsequent HTTP requests with hard-coded paths (that do not start with /memos/) and with ```https://domain-name.com/memos``` as the referer will request resources to render the page. These new requests wind up going to the ```location / block``` in the nginx config file, as ```/memos/``` is not included in the URI, and they are unlikely to be resolved correctly. This explains why you get a blank page.

I would suggest using ```memos.domain-name.com``` instead of ```domain-name.com/memos```. Otherwise, you would need to change the code to ensure that ```/memos/``` is prefixed whenever a path is generated in the backend application.

**Comment by VictorLamoine** [comment]
https://github.com/usememos/memos/pull/1806 it has been reverted, does anyone have a solution?

**Comment by edo0** [comment]
I can confirm this problem persists on the latest version of memos
Would be worth reopening the issue
