### ISSUE TITLE
升级0.13.2会出现无法登录的BUG

### ISSUE THREAD

**Issue by jxjxjhjh** [usememos/memos#1889]
### Describe the bug

docker 0.13.1升级到0.13.2，打开页面自动跳转注册为管理员界面，无论怎样都只能打开这个界面，但是原来的账户登陆不了，新账户也会提示错误。

### Steps to reproduce

很奇怪的问题

**Comment by chencd97** [comment]
我也是，我还以为是我的nginx配置出现了问题，但是没有

![image](https://github.com/usememos/memos/assets/15999183/bdfaec3b-14c9-45f9-bb33-b9e4423f3655)

**Comment by Nyar233** [comment]
same

**Comment by harveyTon** [comment]
Same bug

**Comment by gbaoh1** [comment]
Same for me.
Works great before upgrade.

**Comment by boojack** [comment]
试试清空浏览器缓存，或者通过无痕模式窗口打开页面

**Comment by gbanyan** [comment]
I open the page in an incognito window but the bug still existed.

**Comment by tianyunperfect** [comment]
是tag表被锁住的问题，重启服务就好了，很奇怪

**Comment by athurg** [comment]
This issue may caused by the token validation on */api/v1/status*.

This API should work on both anonymous or authenticated mode.

But if someone provide an invalid token, this API will enter *authenticated* mode, and return error because token is invalid. This always happens on such as token expired or other reasons.

While this API return an error, the frontend code will auto enter a non-initial mode, which looks like you can only signup a new host user instead of just sign in a exists user.
