### ISSUE TITLE
首页视频无法正常播放

### ISSUE THREAD

**Issue by wayner6** [usememos/memos#2134]
### Describe the bug

写备忘时上传了一个视频，提交之后，点击播放无法正常播放，一片黑色界面，有声音，在资源库点击预览下载后的视频可以正常播放

### Steps to reproduce

点击视频播放组件

### Screenshots or additional context

在首页播放时就是这样，一片黑
![image](https://github.com/usememos/memos/assets/88063517/487ad33b-5ee5-4ba4-8dba-00849b3dde64)
另外请求优化一下现在播放组件，播放功能太少了，不能全屏，首页显示效果也很差，希望能和这个模块尽量等宽

**Comment by lincolnthalles** [comment]
The black video is probably not a bug.

As memos doesn't convert file formats, videos must use a container and codecs compatible with [HTML5 specification](https://www.chromium.org/audio-video/) and optimized for streaming. Otherwise, your browser won't be able to play them.

Prefer `mp4`/`webm` containers with `H264`/`H265` for video and `AAC`/`Opus` for audio, and use a sane file bitrate that fits the server *upload* bandwidth, so the video won't buffer all the time.

Use Handbrake, VidCoder or Staxrip if your media needs conversion.

---

But I agree that the small video player needs some attention, as it's not a pleasant experience. That suits a feature request.

**Comment by wayner6** [comment]
Thanks. I get it, is there any ways to solve It.🥲

**Comment by shwangdev** [comment]
Any updates for this issue?

**Comment by boojack** [comment]
> As memos doesn't convert file formats, videos must use a container and codecs compatible with [HTML5 specification](https://www.chromium.org/audio-video/) and optimized for streaming. Otherwise, your browser won't be able to play them.
