### ISSUE TITLE
Geo Locations / Geo References

### ISSUE THREAD

**Issue by lovwyr** [usememos/memos#2903]
### Describe the solution you'd like

It would be nice to have an Option to specify Geo references in Memos (esp. for Travel Locations or so) an show an small, OSM, Map in the Sidebar.

### Type of feature

User Interface (UI)

**Comment by MehadND** [comment]
I think a better solution would be to get location from different providers such google maps and paste url in the memo and then add support for it in link previews to show the map/location.

**Comment by liqMix** [comment]
My friend and I were looking for a lightweight application to use for a public travel log that we could host and decided to try this out. Since we wanted to add some geolocation features for tracking our trip I decided to take a shot at integrating it.
Used `leaflet` and `react-leaflet` combined with some public API endpoints for resolving map tiles and location names.

It's definitely a bit shoe-horned and the commit history is a mess but it works for our use-case and you might be able to glean a better integration from its shortcomings.
https://github.com/liqMix/memos
Docker image name: `ghcr.io/liqmix/memos:test`

![image](https://github.com/usememos/memos/assets/19158752/2a53e8e0-0def-4ed4-9974-3cbc451b40ae)

**Comment by MehadND** [comment]
@liqMix Are you planning on implementing this into memos by submitting a PR? If not then I would really like to work on this

**Comment by boojack** [comment]
ready for release
![image](https://github.com/user-attachments/assets/b083c544-5540-42f8-ba54-3acc6c482d82)
