### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by quick-tutoriel** [usememos/memos#2963]
### Describe the bug

When I log in with my login and password, immediately after validation I get this message:

TypeError: Cannot read properties of undefined (reading 'map')
    at Fm (https://memos.xxx.fr/assets/useDebounce-QqQhdCb9.js:1:3255)
    at Xh (https://memos.xxx.fr/assets/index-4qJIwKsf.js:75:21707)
    at Wk (https://memos.xxx.fr/assets/index-4qJIwKsf.js:77:48469)
    at Vk (https://memos.xxx.fr/assets/index-4qJIwKsf.js:77:43777)
    at Uk (https://memos.xxx.fr/assets/index-4qJIwKsf.js:77:43700)
    at Jk (https://memos.xxxx.fr/assets/index-4qJIwKsf.js:77:43542)
    at Ok (https://memos.xxxx.fr/assets/index-4qJIwKsf.js:77:39552)
    at Fk (https://memos.xxxx.fr/assets/index-4qJIwKsf.js:77:40446)
    at jg (https://memos.xxxxx.fr/assets/index-4qJIwKsf.js:75:3532)
    at https://memos.xxxxx.fr/assets/index-4qJIwKsf.js:77:37702

_PS: the xxxx replaces the address of my site_

### Steps to reproduce

I make the same mistake every time I connect.

### The version of Memos you're using

0.19.1

### Screenshots or additional context

![erreur-memos-1](https://github.com/usememos/memos/assets/4949554/8b48bffb-664e-416b-81eb-b1e7409d0cc2)

**Comment by boojack** [comment]
Please try to open it in incognito window.

**Comment by adriangauri** [comment]
> Please try to open it in incognito window.

I have the same error output in my browser but not when I log into the app with my credentials, but I have it when I click "Click to fetch more" (to retrieve earlier notes in my timeline). I've tried logging into my Memos in the incognito browser window, but the result is the same. So, it turns out, it has nothing to do with the cache problem in my case.
I use the default SQLite option as my database. And I've just upgraded to the new version of Memos today. I didn't have this problem in my previous version/installation. Just decided to upgrade today to check out the new features :) 
Has anyone figured out a solution to this "error" problem?

**Comment by buptweixin** [comment]
I encountered the same problem after updating the docker image to 0.19.1.

**Comment by adriangauri** [comment]
I've redeployed the container several times (was experimenting with the nginx reverse proxy) and the "Fetch more" now works well, but suddenly my "Archived" section started giving the same "Type error". And it seems to be only the issue in the WebApp, because the same instance of memos accessed via the Android App doesn't have this error.

**Comment by boojack** [comment]
Maybe related to https://github.com/usememos/memos/issues/2988?

**Comment by adriangauri** [comment]
> Maybe related to #2988?

Well, for me it's easier than that: currently only opening the "Archived" section throws this kind of error for some reason. And it's only on the WebApp, like I said. In the Android client, everything seems to work properly.

**Comment by quick-tutoriel** [comment]
Hello,

solved with version V0.20

Sincerely

**Comment by adriangauri** [comment]
> Hello,
> 
> solved with version V0.20
> 
> Sincerely

Thanks a lot for the work you're doing! I really like Memos, and it's great news that now this little issue has been fixed!
