### ISSUE TITLE
關於markdown無法定位圖片位置的問題

### ISSUE THREAD

**Issue by chenfolk** [usememos/memos#2977]
### Describe the solution you'd like

在 https://github.com/usememos/memos/issues/2793 問題中提到，markdown無法定位圖片位置的問題
我在 https://www.mdeditor.tw/ 中的第 6 行、第 21 行、第 128 行的指令，看到它的右邊就可以正確的定位與顯示圖片，雖然它是外部連結，但，是否只要改成使用內部連結，就可以解決圖片的定位問題了。

目前我可以用以下的方法處理，但希望系統本身可以自動帶上內建的圖片連結，且最下方的圖片不需要顯示。
http://folkrt.myds.me:5230/m/4UJUJLRU6yAjMMrGFfp6DG

### Type of feature

User Interface (UI)

**Comment by boojack** [comment]
> 希望系統本身可以自動帶上內建的圖片連結，且最下方的圖片不需要顯示。

You can also remove the resources below when editing the memo so that they don't show up at the bottom.

IMO, we support markdown image syntax, but do not recommend it because it is difficult to track which memo the image belongs to.

**Comment by chenfolk** [comment]
下面這是插入memo在文章中的指令格式
![[memos/Z6iubvaYER4dzD5Pga5pNJ]]

只需要比照memo連結的兩種方式做修改，讓圖片也有兩種方式，看是要像雙鏈一樣顯示在最下面，還是像一般memo顯示在中間的指定處，就可以達成功能需求了
![](memos/o/r/nMkb3BQVhaMChcBdc8t2ZT)

**Comment by perfy576** [comment]
> 下面這是插入memo在文章中的指令格式 `![[memos/Z6iubvaYER4dzD5Pga5pNJ]]`
> 
> 只需要比照memo連結的兩種方式做修改，讓圖片也有兩種方式，看是要像雙鏈一樣顯示在最下面，還是像一般memo顯示在中間的指定處，就可以達成功能需求了 `![](memos/o/r/nMkb3BQVhaMChcBdc8t2ZT)`



> > 希望系統本身可以自動帶上內建的圖片連結，且最下方的圖片不需要顯示。
> 
> You can also remove the resources below when editing the memo so that they don't show up at the bottom.
> 
> IMO, we support markdown image syntax, but do not recommend it because it is difficult to track which memo the image belongs to.

The current implementation is that the image will be automatically uploaded, but it always stays at the bottom and cannot be hidden. However, I would like the image to display a small thumbnail on the editing page after it is uploaded (so that when there are many images, I can quickly identify which one it is). I should be able to click on it to copy the Markdown formatted link, which I can then paste wherever I want it to appear.
After saving and publishing, the images uploaded at the bottom should not be displayed on the official note viewing page. Only the images inserted by the user should be shown.
