### ISSUE TITLE
Hope to increase the comment button or logo

### ISSUE THREAD

**Issue by mengnimen** [usememos/memos#3014]
### Describe the solution you'd like

I am a new user. I took a long time to find the comments. You can comment only by clicking the time. It is difficult for new users to find that you can comment here.

### Type of feature

User Interface (UI)

**Comment by thedavidweng** [comment]
I thought the comment feature was removed in v0.17.0 because I can't find it anywhere even in the documentation! I just found it after seeing your issue!!! Thank you!!
---
I also think there should be a separate comment button, which is the same as the response, and I think it's best to provide the option of whether to display comments all the time in the administrator's settings.

**Comment by Aadityajoshi151** [comment]
+1 for this.
I had no idea about the comment feature and only got to know after reading the issue. It indeed is sort of hidden and needs to be easier to see/find.

**Comment by sebastienvermeille** [comment]
+1 I was about to ask the "comment feature" and discovered it by accident in this thread 👍

I am willing to contribute to this project so I will try to open a PR for this, I hope maintainers will be ok with it.

(My idea is to simply add an bubble icon  to target comments as a first shot)

**Comment by MehadND** [comment]
@sebastienvermeille @Aadityajoshi151 @thedavidweng @mengnimen how's this 

https://discord.com/channels/1017113925776588902/1053904069745442846/1213170156902027326

**Comment by boojack** [comment]
Updated with https://github.com/usememos/memos/commit/9a8a1d017e06afe289362fd3b3515abcb5a522fa

https://github.com/usememos/memos/assets/24653555/d5280278-2c9b-4118-b808-18877ffe4a0d

**Comment by sebastienvermeille** [comment]
looks great thank you!
