### ISSUE TITLE
Make the editor view resizable or support full screen

### ISSUE THREAD

**Issue by callkalpa** [usememos/memos#3084]
### Describe the solution you'd like

It would be great if the editor space keeps on growing for larger memos. This is applicable both when creating and editing a memo. For lengthy memos the space is limited and the vertical scroll bar needs to be used. If it is possible to make the editor window resizable or to allow have full screen, that would be helpful.

### Type of feature

User Interface (UI)

### Additional context

I am having lists and todos which are a bit lengthy, then I need arrange them under sub sections inside the memo. If I can have more viewing space, it is easier for me to take a look at more items in a glance and rearrange efficiently.

![image](https://github.com/usememos/memos/assets/504756/956de79d-6d68-42a8-a5df-9e36ea41b0f0)

**Comment by RaphaelPour** [comment]
IIRC the editor view was once resizable and bigger (unfortunately I can't find the commit,tag,mr...) and was dropped because of issues with non-latin letters (chinese i guess).

Maybe someone can provide the issue/mr, so we could discuss how to implement the feature in a way the old bugs wouldn't come back :thinking: 

Anyway, I'd also appreciate to have a greater editor view :+1:

**Comment by arthuragone** [comment]
Completely agree, I don't get why when editing the view is different from the initial writing.

**Comment by the94air** [comment]
unstale pls
