### ISSUE TITLE
Can't load images when sharing notes

### ISSUE THREAD

**Issue by wzc90** [usememos/memos#3093]
### Describe the bug

当使用图片分享笔记时，如果笔记中含有`![]()`这样的图片链接，这个图片无法在分享的图片中加载。

### Steps to reproduce

1. 编写一条笔记，含有`![]()`图片链接，这时图片可见
2. 点击分享笔记，选择图片，此时图片仍然可见，点击图片下载
3. 打开下载的图片，发现此图片无法加载

### The version of Memos you're using

0.20.1

**Comment by YohannKovacs** [comment]
From what i have observed, this happens when the servers serving the requested image have CORS disabled.
When the CORS headers are present on the requested resource, there are no issues.
This might be a problem since most images are hosted on CDN's, which do not set the CORS headers.

**Comment by YohannKovacs** [comment]
@boojack I would like to contribute, but would require some help since I'm not sure how to resolve this. Going through the code, it seems like there is a problem with the sanitization of the image content. 
I've tested without the Sanitization code and found that it works fine. Since we are using a third party sanitizer, i think the problem would be resolved if we switch over to something else or implement our own.

Image with sanitization code
![memos-3_27_2024, 10_44_08 PM](https://github.com/usememos/memos/assets/72270440/44cbca80-f13e-4b6d-8fbe-90b8b49b17df)


Image without sanitization code
![memos-3_27_2024, 10_43_18 PM](https://github.com/usememos/memos/assets/72270440/a7859155-9931-4674-84be-a6e5b7fa823b)

**Comment by YohannKovacs** [comment]
I'd like to add that this issue only occurs if the image is being fetched from CDN's which haven't enabled CORS , since we do sanitization after running into CORS policy error

**Comment by wzc90** [comment]
@YohannKovacs @boojack I found that the bug still exists now when using Safari on MacBook,  but on other browsers the bug is fixed!

**Comment by YohannKovacs** [comment]
@wzc90 have you tried with other image uri's as well? I just tested on an older version of safari (15.6), and it works there.

**Comment by wzc90** [comment]
@YohannKovacs That's the problem.

**Comment by YohannKovacs** [comment]
@wzc90 Can you check the live demo as well? Surprisingly ,I tested on the live demo and found it to be working.

**Comment by wzc90** [comment]
@YohannKovacs Just checked the live demo.It doesn't work for my Safari , the downloaded image was transparent too.
![memos-3_30_2024, 6_03_15 PM](https://github.com/usememos/memos/assets/108047478/7a69b07f-1829-4acc-b9da-9779d1e0e775)

**Comment by YohannKovacs** [comment]
I believe the issue may have something to do with this [`canvas.toDataUrl()`](https://github.com/usememos/memos/blob/edc7645086d285f50e484861705ffee3a626f97a/web/src/labs/html2image/index.ts#L101C1-L104C3). 
As far as I can understand, when we try to draw a _tainted canvas_, i.e. using cross-origin images within that canvas, a *security error* is encountered within safari. The `origin-clean` flag is set to false which I guess is not allow `canvas.toDataUrl()`  to work as intended in later versions of safari. [Reference](https://html.spec.whatwg.org/multipage/canvas.html#security-with-canvas-elements)

I have checked with safari v16, but won't be able to test with newer versions since I do not have physical access to a mac.
![Screenshot 2024-03-30 152949](https://github.com/usememos/memos/assets/72270440/492a5212-585d-4622-ba0c-b20d29ddd5a2)
