### ISSUE TITLE
Release compiled frontend

### ISSUE THREAD

**Issue by johndo100** [usememos/memos#3107]
### Describe the solution you'd like

It would be great if you release compiled frontend.
I'm running memos on my FreeBSD machine, I can not build frontend because pnpm seems doens't support FreeBSD very well. I was build frontend on other Linux machine then copy it over.
If you have time, please consider release compiled backend and frontend.
Thank you very much!

### Type of feature

Other

**Comment by Yarg-mirror** [comment]
While waiting for an answer, here is the "best" solution I found so far since I am in a similar use case (mostly wanting to use memos outside of a docker container):
- download the whole project and go in it's root folder
- build it with docker
- run the newly build image
- get the content of the /usr/local/memos directory
- stop the container
- delete it
- use the file like you want

```bash
wget https://github.com/usememos/memos/archive/refs/tags/v0.20.1.tar.gz
tar -xf v0.20.1.tar.gz
cd memos-0.20.1
docker build -t memos .
cd ~
docker run --name memos memos:latest
docker cp memos:/usr/local/memos .
docker stop memos
docker rm memos
docker image rm memos:latest
```
then you will have the memos binary and the frontend in the dist directory of your home.

**Comment by johndo100** [comment]
Thank you!
I build it on another computer with docker.
It's not a priority but it will more convenient if there is a file that we can download.

**Comment by Yarg-mirror** [comment]
Definitly!

**Comment by k0baya** [comment]
Actually, you can use the pre-built files to run memos. I have tried to build it automatically with GitHub Actions, and it works. You can find the pre-built files at this link: [k0baya/memos-freebsd](<https://github.com/k0baya/memos-freebsd>).

**Comment by johndo100** [comment]
Thank you, I'll look into it.
