### ISSUE TITLE
Hide users list on home page ?

### ISSUE THREAD

**Issue by Lordingard** [usememos/memos#3265]
### Describe the solution you'd like

Hello Memos team,
I have just installed Memos on my Docker server and I see that the list of users appears at home when not logged in. Is there the possibility of hiding the list of users, or even redirecting directly to the login page and deactivating the main page?
Thanks !

### Type of feature

User Interface (UI)

**Comment by shomilsaini** [comment]
This is critical if someone is exposing the server to internet. Why is this closed?
Also, cannot remove the login/register button when Oauth2 is enabled.

Both critical issues. Please fix. Thanks

**Comment by shomilsaini** [comment]
I am baffled that this is closed. Why would there be a need to show users without login? Especially if they have no notes that are public. Please add the functionality to remove this section from public page, or better allow admins to set private only servers where nothing is public and without login everything goes to login page,

Thanks

**Comment by fuad00** [comment]
Any updates on this?

**Comment by RoccoSmit** [comment]
Not sure if i'm looking in the right place, but from what I can tell the user list was removed from the explore screen since v0.22.0 as part of [this](https://github.com/usememos/memos/commit/9265b8e2bd29dd8ab3731d538903ee0495a1aa35#diff-d7f046764dc130767d5194380184aad0a20dd3af33db8442aca01049518abbff) commit
