### ISSUE TITLE
真的太垃圾了，建议回退0.21版本吧

### ISSUE THREAD

**Issue by m1732948116** [usememos/memos#3501]
### Describe the solution you'd like

越做越垃圾，最新连时间线都改废了
多级标签真的很有用，而且最新的标签也不按中文首字母排序毫无规律让人怎么找？
还是加点使用的功能吧，比如2FA

### Type of feature

User Interface (UI)

### Additional context

我已经麻了

**Comment by flyklmwl** [comment]
我觉得他说得有点道理 ， 主要是东西多了，根本就没有一个有效的组织方式， 以前把快捷方式删了。 现在又把多级标签删了。你这memos功能就是让人当剪贴板用的啊？

**Comment by m1732948116** [comment]
> 提建议就好好提，人家开源没收你一毛钱，垃圾别张嘴就来

我知道你很急，但你先别急

**Comment by m1732948116** [comment]
上个版本我就提过建议了，但是人家直接关闭了也没有个解释

**Comment by michaelien** [comment]
> I made suggestions in the last version, but they shut it down without any explanation.

@m1732948116 Are you referring to this issue https://github.com/usememos/memos/issues/2884#issuecomment-1921074801? It looks like @boojack closed it because it duplicates another one and he provided the link to the original.

By the way, I think it's a good habit to check for existing issues before creating a new one, rather than just making one with little information. Also, this issue doesn't provide sufficient details about the _enhancement_. If you really want to solve the problem, please consider adding more information first.

**Comment by boojack** [comment]
@m1732948116 All versions are available in the docker hub. You can always choose the one you like that suits you. And please **DO NOT** create such meaningless issues.

**Comment by lufan-cn** [comment]
> 完完全全是负优化，退回`v0.21`了

想请问一下怎么回到v0.21呢，我也想退回

**Comment by erbanku** [comment]
> > 完完全全是负优化，退回`v0.21`了
> 
> 想请问一下怎么回到v0.21呢，我也想退回

You can revert to the `v0.21` by running the following command.
```
docker run neosmemo/memos:0.21
```

If you hosted your instance on [fly.io](fly.io), you can achieve this by changing the version number in `fly.toml`. Below is my `fly.toml` file for reference.

<details>
<summary>Details</summary>

```
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'memos-erbanku'
primary_region = 'hkg'

[build]
  image = 'neosmemo/memos:0.21'

[[mounts]]
  source = 'memos_data'
  destination = '/var/opt/memos'

[http_service]
  internal_port = 5230
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
```

</details>
