### ISSUE TITLE
The browser cache is not updated in time

### ISSUE THREAD

**Issue by ddddchende** [usememos/memos#3792]
### Describe the bug

After I edited the content, I clicked Save and then edited it again.
My cache was not updated to the latest edited content, but the content before the edit.
**After I cleared my browser cache and cookies it updated correctly.**

### Steps to reproduce

1. Edit the previous content
2. Save
3. Re-edit the same content. The browser caches the content before "1. Edit" locally.

### The version of Memos you're using.

v0.22.4

**Comment by RoccoSmit** [comment]
What content are you creating? Wasnt able to replicate with memos or comments. Each time save was clicked the local storage record for the memo/comment was removed.

I did notice cancelling an edit does not clear the local storage record so this would create a scenario where if you edit, change content, cancel and edit again you will see the initial edit content rather than the original content

**Comment by RoccoSmit** [comment]
PR for clearing local storage on cancel https://github.com/usememos/memos/pull/3826
