### ISSUE TITLE
I wonder if the latest version doesn't support export anymore

### ISSUE THREAD

**Issue by kangminsukdotcom** [usememos/memos#3878]
### Describe the solution you'd like

I read the release note, and it says the 'export memos' feature is now retired. Does that mean I can no longer export my memos if I upgrade the service?

### Type of feature

User Experience (UX)

**Comment by yihanglee-cn** [comment]
建议停在一个自己合适的版本不要随便更新，你必须要习惯「他想删什么就删什么」。

**Comment by boojack** [comment]
@kangminsukdotcom Some thoughts about data export:
* Memos is a self-hosted service, not an online product. All your data stays on your machine, not on any cloud platform.
* Previous export endpoint included only content, not images or files, and haven't been maintained for a long time.
* Memos offers full API support, including gRPC and RESTful. If you want to access(export) your data, you can always use the API: https://memos.apidocumentation.com/reference#tag/memoservice/GET/api/v1/memos. 

As for how to use the API, you can refer to the documentation or send it to ChatGPT. The AI always offers some good advices.

**Comment by yggcwx** [comment]
> 关于数据导出的一些想法：
> 
> * Memos 是一种自托管服务，而不是在线产品。您的所有数据都保留在您的计算机上，而不是任何云平台上。
> * 以前的导出终端节点仅包含内容，不包括图像或文件，并且已长时间未维护。
> * Memos 提供完整的 API 支持，包括 gRPC 和 RESTful。如果您想访问（导出）您的数据，您可以随时使用 API：https://memos.apidocumentation.com/reference#tag/memoservice/GET/api/v1/memos。
> 
> 至于如何使用 API，可以参考文档或发送给 ChatGPT。AI 总是提供一些好的建议。
The user base of Memos is very large, and it is almost becoming an industry standard. Therefore, I sincerely hope that developers will be more careful when deleting features, otherwise the negative impact on users will be too great.

The export function should not only not be deleted, but also the import function should be added to further improve it. After confirming that this function was deleted, I was very shocked, very incredible.
