### ISSUE TITLE
Healtcheck is not working anymore on version 0.22.5

### ISSUE THREAD

**Issue by mariushosting** [usememos/memos#3886]
### Describe the bug

The healtcheck is not working anymore on the latest version 0.22.5

### Steps to reproduce

    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5230/

works like a charm in the compose with version 0.22.4 not working anymore in version 0.22.5.

### The version of Memos you're using.

0.22.5

**Comment by onee-only** [comment]
Looks like it is related to #3877.

**Comment by stanthewizzard** [comment]
yes same issue
no more healthcheck

**Comment by Promix953** [comment]
Yeah, one guy completely scrapped healthcheck for 21.3MB.

**Comment by stanthewizzard** [comment]
What ?
I don't understand

**Comment by RoccoSmit** [comment]
The Linux distro was changed and the new one does not have the functionality users are using for health checks.

The intent of the change was to reduce the container size hence the reference to 21.3mb.

This issue is closed (due to being a duplicate), but you can follow the status of getting this resolved on the linked issue that is still open. https://github.com/usememos/memos/issues/3877
