### ISSUE TITLE
Support for ActivityPub

### ISSUE THREAD

**Issue by hulb** [usememos/memos#878]
### Is your feature request related to a problem?

No, not a problem. Since memos supports memo sharing to public, it'll be cool if I can share my memo to the federated network like mastodon through ActivityPub protocol.

### Describe the solution you'd like

Adding a new sharing option to share memo to federated network. As an enhancement to it's socialization.

**Comment by skyue** [comment]
provide a example: https://docs.microblog.pub/

**Comment by yinan-c** [comment]
Hey, just came across this, does that mean Fediverse support will be soon? Really looking forward to it.

**Comment by r0bbie** [comment]
Noticed this had been closed, is this feature no longer planned? Would make Memos a very appealing self-hosted single-user microblogging platform, if ActivityPub was supported! Hopeful to perhaps see it at some point :)

**Comment by forksnd** [comment]
@boojack Is ActivityPub for Memos out of scope?

**Comment by webserviceXXL** [comment]
Just had the same idea and found this (closed) issue. But since this issue was closes by a GitHub action and not @boojack directly, I just wanna add some thoughts.

An integration of the ActivityPub protocol would be quite nice, but also a bigger change. 

Rough Technical Considerations

* This would require adding HTTP endpoints for ActivityPub actors, inboxes, and outboxes
* Implementation of JSON-LD handling for ActivityStreams objects
* Authentication and signature verification for secure federation
* Database schema updates to store followers, following relationships, and remote interactions

This could be a bit too much for just one "simple" feature that is used by only some users. A more efficient way would be to use the webhooks and create a post on your favorite ActivityPub client, like Mastodon.

PS: I think I will build a n8n workflow sharing my public memos with my Mastodon profile. If you're interested let me know.

**Comment by webserviceXXL** [comment]
@yinan-c Yes, every Mastodon server does have a public API. You just need an access token for your account.

My n8n workflow is already active and is publishing all public memos with my Mastodon account at https://mastodon.social/deck/@WebPassionist.

![Image](https://github.com/user-attachments/assets/3587f01b-b09a-4cb7-92ef-60de921ea2ab)

**Comment by webserviceXXL** [comment]
@yinan-c I created a short explanation and made the workflow downloadable at https://www.aaartist.dev/share-memos-on-mastodon/
